import "./globals.css";
import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import NavBar from "./components/Navbar";

const nunito = Nunito({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Ecommerce Application4",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${nunito.className}`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
